version: '3.9'

services:
  php:
    build: ./image/php/
    restart: unless-stopped
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./image/nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - php
